name: CI Build

on:
  push:
    branches: [v1, v2, v3, ci-test]
  pull_request:
    branches: [v1, v2, v3]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Use JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage coverage_enable_subprocess coveralls
          pip install -r requirements.txt

      - name: Start test infrastructure
        run: |
          find tests-infra -name compose.yaml -exec docker compose -f {} up -d \;

      - name: Run unit tests
        run: |
          coverage run -m pytest tests

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: python-${{ matrix.python-version }}
          parallel: true

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
